### ISSUE TITLE
emit warning for sharp corners?

### ISSUE THREAD

**Issue by stevengj** [NanoComp/imageruler#15]
Sharp corners are treated as a small lengthscale, proportional to the pixel size.  This is mathematically correct, but might be unexpected for some users.

It might be nice to emit a warning if sharp corners are detected?  Maybe OpenCV has a feature to detect this?

**Comment by mawc2019** [comment]
> Maybe OpenCV has a feature to detect this?

Yes, it was described in this [Issue](https://github.com/NanoComp/photonics-opt-testbed/issues/42).

**Comment by stevengj** [comment]
Probably no longer needed (#30).
