### ISSUE TITLE
use standard python package structure

### ISSUE THREAD

**Issue by stevengj** [NanoComp/imageruler#2]
See https://docs.python-guide.org/writing/structure/ and https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/

cc @mawc2019, @ianwilliamson

**Comment by ianwilliamson** [comment]
Among other things, it needs an `imageruler` subdir that contains all of the python files.

**Comment by stevengj** [comment]
(This repo was just created by [doing `git filter-repo`](https://jeffkreeftmeijer.com/git-extract/) to extract the `ruler` directory from https://github.com/NanoComp/photonics-opt-testbed, with no other cleanup yet other than to add a LICENSE file.)

**Comment by ianwilliamson** [comment]
I somewhat recently released this as a pip-installable package: https://github.com/google/ceviche-challenges If it's helpful, you can use it as a guide / template for setting this up for release. The `setup.py` and the workflows for publishing to pypi on release are probably most useful.
