### ISSUE TITLE
Occasional failures with non-square arrays

### ISSUE THREAD

**Issue by mfschubert** [NanoComp/imageruler#23]
Measuring length scale of non-square arrays seems fail occasionally, perhaps due to some rounding and subsequent off-by-one errors. For example, the shape (40, 40) is fine as is (50, 80), but (40, 80) is problematic. The problem is reproduced in the following colab notebook:

https://colab.research.google.com/drive/1BL_LvPJYmAAdJ2QmvR_BUkB2a-i_VG-Q

It also seems to be pattern-dependent, since the same array shapes do not cause problems with uniform-ones arrays.

![image](https://github.com/NanoComp/imageruler/assets/30735893/61a2e7cd-2663-40cb-ad0f-a028c287cf3f)

**Comment by mawc2019** [comment]
The error occurs when the kernel given by the function `get_kernel(diameter, pixel_size, kernel_shape)` is an empty array, which sometimes happens when each pixel has different sizes along different directions and `diameter` equals `min(pixel_size)`.

**Comment by stevengj** [comment]
Closed by #30
